/**
 * ARS 3.0 Central Check Registry
 * Specification: GLINTBASE_AUDIT_3_0_UPGRADE_SPEC.md
 * Total: 119 Discrete Open Protocol Checks across 4 Layers
 */

import { CheckDefinition, LayerId } from './types.js';

export const ALL_CHECKS: CheckDefinition[] = [
  // ==========================================
  // LAYER 1: DISCOVERY (16 Checks | 20 Base Pts)
  // ==========================================
  {
    id: 'registry-branding',
    name: 'MCP Registry Branding Metadata',
    layer: 'discovery',
    points: 2,
    isBonus: false,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'Verifies name, icon, and description are declared in /.well-known/mcp/manifest.json or /mcp.json.',
    remediationId: 'mcp-manifest',
  },
  {
    id: 'ard-catalog',
    name: 'Agent Resource Discovery (ARD v0.91)',
    layer: 'discovery',
    points: 1,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Probes /.well-known/ard.json or fallback ai-catalog.json enforcing urn:air identifiers.',
    remediationId: 'ard-json',
  },
  {
    id: 'ai-catalog-published',
    name: 'Agent-Card WG Catalog Specification',
    layer: 'discovery',
    points: 1,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Verify /.well-known/ai-catalog.json adhering to the Agent-Card Working Group specification.',
    remediationId: 'ai-catalog',
  },
  {
    id: 'ard-entries-valid',
    name: 'ARD Catalog Entries Validated',
    layer: 'discovery',
    points: 2,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Validates each catalog entry carries displayName, valid mediaType, and resolvable url/data.',
  },
  {
    id: 'ard-trust-manifest',
    name: 'Cryptographic Trust Manifest',
    layer: 'discovery',
    points: 2,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Validates presence of cryptographic signatures or attestation blocks in ARD catalog.',
  },
  {
    id: 'chatgpt-app-listed',
    name: 'OpenAI ChatGPT Directory Listing',
    layer: 'discovery',
    points: 2,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'Checks inclusion and domain verification in the OpenAI ChatGPT App Directory.',
  },
  {
    id: 'brand-search-accuracy',
    name: 'Brand Apex Search Resolution',
    layer: 'discovery',
    points: 3,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'Brand-name queries rank target apex domain as the definitive authoritative origin.',
  },
  {
    id: 'agentic-search-specific',
    name: 'Developer Keyword Discoverability',
    layer: 'discovery',
    points: 3,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'Developer documentation, OpenAPI specs, and MCP endpoints are ranked in top search results.',
  },
  {
    id: 'wikipedia-presence',
    name: 'Wikidata P856 Official Website Claim',
    layer: 'discovery',
    points: 4,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'Verifies Wikipedia/Wikidata authority record has property P856 mapped to apex domain.',
  },
  {
    id: 'mcp-registry-listed',
    name: 'Global MCP Registry Listing',
    layer: 'discovery',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'Verifies domain or server presence in major MCP registries (Smithery, mcp.so, npm).',
  },
  {
    id: 'npm-sdk-package',
    name: 'Official SDK Package Published',
    layer: 'discovery',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Official SDK or CLI package verified under matching package scope or repository link.',
  },
  {
    id: 'agent-rules-repo',
    name: 'Autonomous Agent Instruction Rules',
    layer: 'discovery',
    points: 1,
    isBonus: false,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'static_ast',
    description: 'Repository contains explicit AI agent guidelines (.claude/, .cursor/, .windsurf/ rules).',
    remediationId: 'agent-rules',
  },
  {
    id: 'agent-plugins-repo',
    name: 'Agent-Plugins Schema Compliance',
    layer: 'discovery',
    points: 1,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Verify presence of plugin.json conforming to agent-plugins.org specification.',
  },
  {
    id: 'skills-sh-listed',
    name: 'Skills.sh Verified Publisher',
    layer: 'discovery',
    points: 1,
    isBonus: false,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'Checks skills.sh registry for verified agent skills registered to domain organization.',
  },
  {
    id: 'robots-ai-policy-quality',
    name: 'Tiered robots.txt AI Policy',
    layer: 'discovery',
    points: 2,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Permits answer bots (ClaudeBot, GPTBot, PerplexityBot) while regulating training crawlers.',
    remediationId: 'robots-txt',
  },
  {
    id: 'agentic-search-usecase',
    name: 'Complex Agentic Query Resolution',
    layer: 'discovery',
    points: 6,
    isBonus: false,
    tier: 'beta',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'Evaluates zero-shot search accuracy for multi-step agent queries (held at N/A in standard mode).',
  },

  // ========================================================
  // LAYER 2: ACCESS & UNDERSTANDING (41 Checks | 30 Base Pts)
  // ========================================================
  {
    id: 'content-no-js',
    name: 'Zero-JS Content Readability',
    layer: 'access',
    points: 3,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Clean HTML prose (>500 chars, h1 present, valid heading progression, >5% text density).',
    remediationId: 'content-no-js',
  },
  {
    id: 'page-token-budget',
    name: 'Documentation Page Token Budget',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Extracted text across core documentation stays within the 100k character budget (~25k tokens).',
  },
  {
    id: 'anti-spa-404',
    name: 'Anti-SPA Canary 404 Guard',
    layer: 'access',
    points: 2,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Random canary URLs return genuine HTTP 404/410 rather than soft HTTP 200 SPA shells.',
    remediationId: 'anti-spa-404',
  },
  {
    id: 'llms-txt-exists',
    name: 'Standard llms.txt Context Index',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Standard /llms.txt file is published at apex domain or root directory.',
    remediationId: 'llms-txt',
  },
  {
    id: 'llms-txt-formatting',
    name: 'llms.txt Structure & Links',
    layer: 'access',
    points: 2,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'llms.txt starts with # Heading, contains >=5 non-empty lines, valid markdown links, 100-30k chars.',
  },
  {
    id: 'llms-txt-links-resolve',
    name: 'llms.txt Linked Resources Reachable',
    layer: 'access',
    points: 2,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Canary checks first 5 declared markdown links; all resolve to valid non-SPA content.',
  },
  {
    id: 'markdown-negotiation',
    name: 'Accept: text/markdown Negotiation',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Server returns raw markdown payload when client sends Accept: text/markdown.',
    remediationId: 'markdown-negotiation',
  },
  {
    id: 'markdown-negotiation-vary',
    name: 'Vary: Accept CDN Cache Header',
    layer: 'access',
    points: 1,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Responses negotiated via Accept send Vary: Accept to prevent CDN cache poisoning.',
  },
  {
    id: 'markdown-url-fallback',
    name: 'Raw Markdown (.md) URL Twins',
    layer: 'access',
    points: 2,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Appending .md to content and doc URLs returns raw clean markdown twins.',
  },
  {
    id: 'code-fence-validity',
    name: 'Balanced Column-0 Code Fences',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'All markdown fenced blocks (``` or ~~~) are strictly balanced and properly closed.',
  },
  {
    id: 'openapi-spec',
    name: 'OpenAPI 3.x Machine Specification',
    layer: 'access',
    points: 7,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Valid OpenAPI 3.x schema published at /openapi.json, /swagger.json, or exported in code.',
    remediationId: 'openapi-spec',
  },
  {
    id: 'developer-portal',
    name: 'Self-Serve Developer Portal Path',
    layer: 'access',
    points: 6,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Self-serve developer route discoverable (/developers, /docs, /dashboard, /api-keys).',
  },
  {
    id: 'api-catalog-rfc9727',
    name: 'RFC 9727 API Catalog Linkset',
    layer: 'access',
    points: 2,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'Publishes /.well-known/api-catalog with Accept: application/linkset+json support.',
  },
  {
    id: 'ssl-tls-enforced',
    name: 'Enforced HTTPS / Valid TLS Certificate',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'All HTTP traffic permanently redirects (301/308) to HTTPS with valid TLS.',
  },
  {
    id: 'http2-support',
    name: 'HTTP/2 Protocol Support',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'Web server supports multiplexed HTTP/2 or HTTP/3 transport for agent requests.',
  },
  {
    id: 'cors-headers',
    name: 'CORS Access-Control-Allow-Origin',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'API and catalog endpoints return permissive or configured CORS headers for web agents.',
  },
  {
    id: 'compression-gzip-br',
    name: 'Payload Compression (Gzip / Brotli)',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'Responses support Content-Encoding: gzip or br for efficient token transfer.',
  },
  {
    id: 'clean-semantic-html',
    name: 'Semantic HTML Landmarks',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'HTML structure leverages semantic elements (<main>, <article>, <nav>, <header>).',
  },
  {
    id: 'heading-hierarchy',
    name: 'Strict Heading Level Progression',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Headings do not skip levels (e.g. h1 followed directly by h3 or h4).',
  },
  {
    id: 'meta-description-quality',
    name: 'Authoritative Meta Description',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Meta description exists, length is 50-300 characters, and contains clear descriptive prose.',
  },
  {
    id: 'json-ld-structured-data',
    name: 'JSON-LD Schema.org Metadata',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Homepage and doc pages include JSON-LD schema (WebSite, SoftwareApplication, Organization).',
  },
  {
    id: 'sitemap-xml-present',
    name: 'Standard sitemap.xml Index',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Valid sitemap.xml file accessible at root or declared in robots.txt.',
  },
  {
    id: 'charset-utf8-declared',
    name: 'Explicit UTF-8 Charset Declaration',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Content-Type header or HTML meta tag explicitly declares charset=utf-8.',
  },
  {
    id: 'canonical-url-present',
    name: 'Authoritative Canonical URL Tag',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Every document carries <link rel="canonical"> to eliminate duplicate agent indexing.',
  },
  {
    id: 'content-type-charset',
    name: 'Accurate Content-Type Header',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'HTTP response Content-Type matches actual payload (text/html, text/markdown, application/json).',
  },
  {
    id: 'etag-caching',
    name: 'ETag Cache Validation Support',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'Server returns ETag header allowing conditional 304 Not Modified requests.',
  },
  {
    id: 'cache-control-headers',
    name: 'Explicit Cache-Control Directives',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Static and doc assets specify public max-age caching directives.',
  },
  {
    id: 'response-latency-p95',
    name: 'Fast First-Byte Latency (TTFB < 800ms)',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'P95 response time for documentation pages is under 800ms.',
  },
  {
    id: 'status-code-accuracy',
    name: 'Authentic HTTP Status Codes',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Server does not return 200 for error states or masking real error semantics.',
  },
  {
    id: 'text-density-ratio',
    name: 'High Text-to-HTML Markup Ratio',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Prose text content represents >= 5% of overall page markup size.',
  },
  {
    id: 'pagination-rel-links',
    name: 'Machine Pagination (rel=next/prev)',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'List views and paginated feeds include rel="next" and rel="prev" links.',
  },
  {
    id: 'link-header-canonical',
    name: 'Link HTTP Header for Machine Twins',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Link header points agents to alternative representations (e.g. rel="alternate" type="text/markdown").',
  },
  {
    id: 'dns-caa-record',
    name: 'DNS CAA Security Records',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'Domain has CAA records configured for authorized certificate authority issuance.',
  },
  {
    id: 'security-headers-csp',
    name: 'Standard Security Headers',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Responses include X-Content-Type-Options: nosniff and Referrer-Policy.',
  },
  {
    id: 'security-txt-rfc9116',
    name: 'Security Vulnerability Disclosure (security.txt)',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Publishes /.well-known/security.txt conforming to RFC 9116.',
  },
  {
    id: 'llms-full-txt-present',
    name: 'Comprehensive llms-full.txt Context',
    layer: 'access',
    points: 1,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Optional /llms-full.txt providing consolidated zero-hop documentation context.',
  },
  {
    id: 'markdown-table-syntax',
    name: 'Standard GFM Table Formatting',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'All markdown tables have matching header and body column counts.',
  },
  {
    id: 'relative-link-resolution',
    name: 'Strict Relative URL Resolution',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Documentation markdown avoids unresolvable relative parent hops (../../).',
  },
  {
    id: 'image-alt-prose',
    name: 'Descriptive Image Alt Text',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Informative diagram and architectural images include descriptive alt prose.',
  },
  {
    id: 'plain-text-accessible',
    name: 'Raw Plain Text Endpoint (/raw or text/plain)',
    layer: 'access',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Key documentation articles can be consumed as plain UTF-8 text.',
  },
  {
    id: 'anti-crawler-challenge-free',
    name: 'Unchallenged Agent Scraping for Public Docs',
    layer: 'access',
    points: 2,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'live_probe',
    description: 'Public documentation endpoints do not trigger Cloudflare/Imperva JavaScript captcha walls for AI agents.',
  },

  // =============================================================
  // LAYER 3: USABILITY & INTEROPERABILITY (56 Checks | 40 Base Pts)
  // =============================================================
  // 1. MCP Core & Transports
  {
    id: 'mcp-server-manifest',
    name: 'MCP Server Manifest Available',
    layer: 'usability',
    points: 2,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'MCP server endpoint is live and responds to initialization handshake.',
    remediationId: 'mcp-server',
  },
  {
    id: 'mcp-tools-listing',
    name: 'MCP Tools Catalog (tools/list)',
    layer: 'usability',
    points: 3,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'tools/list returns valid array of tools with schema definitions.',
  },
  {
    id: 'mcp-tools-focus',
    name: 'Kind-Aware Focus (Docs MCP: 1-3 Focused Tools)',
    layer: 'usability',
    points: 3,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'docs',
    evaluatorMode: 'both',
    description: 'Docs MCPs provide 1 to 3 focused search/retrieval tools to prevent agent prompt pollution.',
  },
  {
    id: 'mcp-tools-breadth',
    name: 'Kind-Aware Breadth (Product MCP: Rich Toolset)',
    layer: 'usability',
    points: 3,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'product',
    evaluatorMode: 'both',
    description: 'Product MCPs provide >=3 tools or code-mode dispatcher for complete workflow execution.',
  },
  {
    id: 'mcp-tools-schema-strict',
    name: 'Strict JSON Schema Typing for MCP Parameters',
    layer: 'usability',
    points: 2,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'All tool inputSchema definitions declare type, properties, and required arrays.',
  },
  {
    id: 'mcp-tools-readonly-hint',
    name: 'MCP Tool readOnlyHint Annotations',
    layer: 'usability',
    points: 2,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Safe query and read tools declare readOnlyHint: true to skip confirmation prompts.',
  },
  {
    id: 'mcp-tools-destructive-hint',
    name: 'MCP Tool destructiveHint Annotations',
    layer: 'usability',
    points: 2,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Mutating or deletion tools declare destructiveHint: true for safety controls.',
  },
  {
    id: 'mcp-auth-requirement',
    name: 'Kind-Aware MCP Auth Policy',
    layer: 'usability',
    points: 2,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Docs MCPs must be public zero-auth; Product MCPs must enforce OAuth metadata.',
  },
  {
    id: 'mcp-transport-streamable',
    name: 'Streamable HTTP MCP Transport (/api/mcp)',
    layer: 'usability',
    points: 3,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Mounts modern Streamable HTTP MCP transport handler for stateless agent queries.',
    remediationId: 'mcp-server',
  },
  {
    id: 'mcp-transport-sse',
    name: 'Server-Sent Events (SSE) MCP Transport',
    layer: 'usability',
    points: 2,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Supports SSE connection channel for streaming tool updates and execution logs.',
  },
  {
    id: 'mcp-app-registry',
    name: 'MCP App UI Resource Schemas',
    layer: 'usability',
    points: 4,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Declares _meta.ui.resourceUri with ui:// schemes for in-agent visual rendering.',
  },
  {
    id: 'mcp-apps-ui-quality',
    name: 'MCP App HTML Profile Compliance',
    layer: 'usability',
    points: 4,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Served UI resources adhere to text/html;profile=mcp-app specifications.',
  },
  {
    id: 'mcp-view-csp',
    name: 'In-Agent UI Frame CSP Policy',
    layer: 'usability',
    points: 4,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'CSP frame-ancestors permits chatgpt.com, claude.ai, and approved agent hosts.',
  },
  {
    id: 'mcp-prompts-listing',
    name: 'MCP Prompt Templates (prompts/list)',
    layer: 'usability',
    points: 1,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Exposes curated prompt templates guiding agents on workflow execution patterns.',
  },
  {
    id: 'mcp-resources-listing',
    name: 'MCP Dynamic Resources (resources/list)',
    layer: 'usability',
    points: 1,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Exposes structured read-only data files via resources/list.',
  },
  {
    id: 'mcp-error-reporting',
    name: 'Standard JSON-RPC 2.0 Error Codes',
    layer: 'usability',
    points: 2,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Tool failures return standard JSON-RPC error codes with clear error messages.',
  },
  {
    id: 'mcp-protocol-version',
    name: 'MCP Specification Protocol Versioning',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Client/Server handshake negotiates supported protocolVersion string.',
  },
  {
    id: 'mcp-sampling-support',
    name: 'MCP Sampling Capability',
    layer: 'usability',
    points: 2,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Server declares sampling capability allowing server to request LLM generations via client.',
  },
  {
    id: 'mcp-roots-support',
    name: 'MCP Roots Capability',
    layer: 'usability',
    points: 1,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Server advertises roots capability for workspace filesystem context.',
  },
  {
    id: 'mcp-logging-notifications',
    name: 'MCP Notifications / Logging',
    layer: 'usability',
    points: 1,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Server emits structured progress notifications during long-running tool execution.',
  },

  // 2. WorkOS auth.md & Machine Authentication
  {
    id: 'auth-md-structure',
    name: 'WorkOS auth.md 8-Stage Canonical Structure',
    layer: 'usability',
    points: 2,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Validates 8 canonical stages: Discover, Pick Method, Register, Claim, Exchange, Use, Errors, Revocation.',
    remediationId: 'auth-md',
  },
  {
    id: 'auth-md-stage-discover',
    name: 'auth.md Stage 1: Discovery Endpoints',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'auth.md documents discovery URLs for OAuth / PRM metadata.',
  },
  {
    id: 'auth-md-stage-methods',
    name: 'auth.md Stage 2: Authentication Methods',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'auth.md specifies supported methods (id-jag, service_auth, anonymous).',
  },
  {
    id: 'auth-md-stage-register',
    name: 'auth.md Stage 3: Client Registration',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'auth.md contains fenced HTTP request and JSON response blocks for machine registration.',
  },
  {
    id: 'auth-md-stage-claim',
    name: 'auth.md Stage 4: Token Claim Protocol',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'auth.md documents claim_token, user_code, and verification_uri flow.',
  },
  {
    id: 'auth-md-stage-exchange',
    name: 'auth.md Stage 5: Token Exchange Grant',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'auth.md details JWT-bearer token exchange grant URN and parameters.',
  },
  {
    id: 'auth-md-stage-use',
    name: 'auth.md Stage 6: Bearer Header Invocation',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'auth.md shows clear examples of Authorization: Bearer <token> usage.',
  },
  {
    id: 'auth-md-stage-errors',
    name: 'auth.md Stage 7: Auth Error Enumeration',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'auth.md enumerates invalid_claim_token, claimed_or_in_flight, authorization_pending.',
  },
  {
    id: 'auth-md-stage-revocation',
    name: 'auth.md Stage 8: Token Revocation & Security',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'auth.md specifies secevent+jwt token revocation endpoints and event formats.',
  },
  {
    id: 'auth-md-walkthrough-simulation',
    name: 'auth.md Read-Only GET Simulation',
    layer: 'usability',
    points: 2,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Executes non-mutating GET simulation: reads auth.md, follows RFC 9728 PRM and RFC 8414 AS metadata hops.',
  },
  {
    id: 'agent-auth-www-authenticate',
    name: 'WWW-Authenticate Resource Metadata Header',
    layer: 'usability',
    points: 1,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Inspects 401 responses on API routes for WWW-Authenticate: Bearer resource_metadata="...".',
  },
  {
    id: 'oauth-rfc8414-metadata',
    name: 'RFC 8414 OAuth Authorization Server Metadata',
    layer: 'usability',
    points: 2,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Publishes /.well-known/oauth-authorization-server with token_endpoint and agent_auth metadata.',
  },
  {
    id: 'oauth-rfc9728-prm',
    name: 'RFC 9728 Protected Resource Metadata (PRM)',
    layer: 'usability',
    points: 2,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Publishes /.well-known/oauth-protected-resource with authorization_servers array.',
  },
  {
    id: 'auth-bearer-token-support',
    name: 'Standard Bearer Token API Protection',
    layer: 'usability',
    points: 2,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'API routes authenticate incoming requests via Authorization: Bearer header.',
  },
  {
    id: 'auth-scoped-permissions',
    name: 'Granular Scope Declarations',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'API routes and OpenAPI document fine-grained scope permissions (e.g. read:items, write:items).',
  },

  // 3. WebMCP & Browser Interaction
  {
    id: 'webmcp',
    name: 'W3C WebMCP DOM & Script Declarations',
    layer: 'usability',
    points: 5,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Inspects HTML/JS for window.modelContext tool registrations and form toolname attributes.',
  },
  {
    id: 'webmcp-model-context',
    name: 'window.modelContext API Registration',
    layer: 'usability',
    points: 2,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Browser client registers tools dynamically via window.modelContext.registerTool().',
  },
  {
    id: 'webmcp-form-attributes',
    name: 'Declarative HTML Form Agent Attributes',
    layer: 'usability',
    points: 2,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'HTML form tags provide declarative toolname and tooldescription attributes for agent interactions.',
  },

  // 4. API Usability & Standard Contracts
  {
    id: 'api-operation-ids',
    name: 'Unique operationId in OpenAPI Specification',
    layer: 'usability',
    points: 2,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'All OpenAPI operations declare unique, clean camelCase or snake_case operationIds.',
  },
  {
    id: 'api-json-schemas',
    name: 'Strict JSON Schemas for Request Payloads',
    layer: 'usability',
    points: 2,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Request bodies declare explicit schema properties and required field constraints.',
  },
  {
    id: 'api-error-schemas',
    name: 'Typed Error Response Schemas',
    layer: 'usability',
    points: 2,
    isBonus: false,
    tier: 'required',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Error responses declare structured JSON bodies with error codes and diagnostic messages.',
  },
  {
    id: 'api-idempotency-keys',
    name: 'Idempotency-Key Header Support',
    layer: 'usability',
    points: 2,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'POST/PUT mutation routes accept Idempotency-Key header to prevent duplicate execution.',
  },
  {
    id: 'api-rate-limit-headers',
    name: 'Standard RateLimit-* Response Headers',
    layer: 'usability',
    points: 2,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'API responses return RateLimit-Limit, RateLimit-Remaining, and RateLimit-Reset headers.',
  },
  {
    id: 'api-curl-examples',
    name: 'Executable cURL Request Examples',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Documentation provides copy-paste ready cURL examples with realistic dummy values.',
  },
  {
    id: 'api-code-samples',
    name: 'Multi-Language SDK Code Samples',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Documentation displays TypeScript/JavaScript, Python, and Go code snippets.',
  },
  {
    id: 'api-versioning-in-uri',
    name: 'Explicit API Versioning Strategy',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'API paths incorporate explicit version segment (/v1/...) or Accept header versioning.',
  },
  {
    id: 'api-search-endpoint',
    name: 'Global Search / Filter API Endpoint',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Provides queryable search/filter endpoint (/search or /filter) for autonomous agent discovery.',
  },
  {
    id: 'api-rfc7807-problem-details',
    name: 'RFC 7807 Problem Details for HTTP APIs',
    layer: 'usability',
    points: 2,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Error responses use application/problem+json MIME type with type, title, status, and detail.',
  },
  {
    id: 'api-bulk-batch-operations',
    name: 'Batch / Bulk API Endpoints',
    layer: 'usability',
    points: 1,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Offers bulk create/update endpoints (/batch) to conserve agent roundtrips.',
  },
  {
    id: 'api-pagination-cursor',
    name: 'Cursor-Based Pagination for Large Collections',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'High-volume list endpoints provide cursor or starting_after pagination.',
  },
  {
    id: 'api-webhook-declarations',
    name: 'Webhook Event Catalog in OpenAPI',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'OpenAPI 3.1 webhooks block documents outbound event schemas and HMAC signatures.',
  },
  {
    id: 'api-openapi-3-1-strict',
    name: 'OpenAPI 3.1 Dialect Compliance',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Validates schema against full OpenAPI 3.1 specification including JSON Schema 2020-12.',
  },
  {
    id: 'api-sandbox-environment',
    name: 'Public Testnet / Mock Sandbox URL',
    layer: 'usability',
    points: 2,
    isBonus: true,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Provides a sandbox or mock environment (api.sandbox.acme.com) for safe agent experimentation.',
  },
  {
    id: 'api-sdk-documentation',
    name: 'SDK Setup & Installation Instructions',
    layer: 'usability',
    points: 1,
    isBonus: false,
    tier: 'recommended',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'Documentation documents npm/pip install commands and client initialization snippets.',
  },
  {
    id: 'api-graphql-schema',
    name: 'GraphQL Schema Introspection or SDL',
    layer: 'usability',
    points: 1,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'GraphQL endpoints provide introspection schema or published schema.graphql.',
  },
  {
    id: 'api-grpc-reflection',
    name: 'gRPC Server Reflection / Protobuf Definitions',
    layer: 'usability',
    points: 1,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'generic',
    evaluatorMode: 'both',
    description: 'gRPC services provide server reflection or downloadable .proto files.',
  },

  // ==============================================================
  // LAYER 4: PAYMENTS & MACHINE COMMERCE (6 Checks | 10 Base Pts)
  // (Subject to Payments "OR-Scoring" Rule)
  // ==============================================================
  {
    id: 'acp-support',
    name: 'Agentic Commerce Protocol (ACP /checkout_sessions)',
    layer: 'payments',
    points: 3,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'ecommerce',
    evaluatorMode: 'both',
    description: 'Implements ACP session creation and preflight validation at /checkout_sessions.',
  },
  {
    id: 'acp-delegate-payment',
    name: 'ACP Delegated Payment Authorization',
    layer: 'payments',
    points: 3,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'ecommerce',
    evaluatorMode: 'both',
    description: 'Implements /agentic_commerce/delegate_payment for autonomous transaction execution.',
  },
  {
    id: 'ucp-support',
    name: 'Universal Commerce Protocol (/.well-known/ucp)',
    layer: 'payments',
    points: 3,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'ecommerce',
    evaluatorMode: 'both',
    description: 'Publishes /.well-known/ucp with ISO date versioning and merchant capabilities.',
  },
  {
    id: 'ap2-support',
    name: 'Google Agent Payments Protocol (AP2 Mandates)',
    layer: 'payments',
    points: 3,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'ecommerce',
    evaluatorMode: 'both',
    description: 'Supports SD-JWT signed authorization mandates under Google Agent Payments Protocol.',
  },
  {
    id: 'x402-support',
    name: 'HTTP 402 Micropayments (x402 Header)',
    layer: 'payments',
    points: 2,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'ecommerce',
    evaluatorMode: 'both',
    description: 'Returns HTTP 402 with PAYMENT-REQUIRED header for per-call autonomous micropayments.',
  },
  {
    id: 'mpp-support',
    name: 'Machine Payments Protocol (MPP x-payment-info)',
    layer: 'payments',
    points: 2,
    isBonus: true,
    tier: 'emerging',
    targetKind: 'ecommerce',
    evaluatorMode: 'both',
    description: 'Declares x-payment-info OpenAPI extensions for machine pricing tiers.',
  },
];

// Helper Query Methods
export function getAllChecks(): CheckDefinition[] {
  return ALL_CHECKS;
}

export function getCheckById(id: string): CheckDefinition | undefined {
  return ALL_CHECKS.find(c => c.id === id);
}

export function getChecksForLayer(layer: LayerId): CheckDefinition[] {
  return ALL_CHECKS.filter(c => c.layer === layer);
}

export function getBonusChecks(): CheckDefinition[] {
  return ALL_CHECKS.filter(c => c.isBonus);
}

export function getChecksForSpec(spec: 'ars' | 'strict' | 'core'): CheckDefinition[] {
  if (spec === 'core') {
    // 12 Essential checks
    const coreIds = new Set([
      'robots-ai-policy-quality',
      'ard-catalog',
      'brand-search-accuracy',
      'content-no-js',
      'anti-spa-404',
      'llms-txt-exists',
      'markdown-negotiation',
      'openapi-spec',
      'mcp-server-manifest',
      'mcp-tools-listing',
      'auth-bearer-token-support',
      'api-json-schemas',
    ]);
    return ALL_CHECKS.filter(c => coreIds.has(c.id));
  }
  return ALL_CHECKS;
}
