/**
 * Git Utilities for Glintbase CLI.
 * Provides safe, robust Git workspace inspection, branching, staging, and commits.
 */

import { execSync } from 'child_process';

export interface GitBranchResult {
  branch: string;
  created: boolean;
  previousBranch?: string;
}

export interface PrSnippet {
  branch: string;
  baseBranch: string;
  gitPushCmd: string;
  ghPrCmd: string;
}

/**
 * Check if a directory is inside a Git working tree.
 */
export function isGitRepository(cwd: string = process.cwd()): boolean {
  try {
    const output = execSync('git rev-parse --is-inside-work-tree', {
      cwd,
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    return output === 'true';
  } catch {
    return false;
  }
}

/**
 * Get current checked out branch name.
 */
export function getCurrentBranch(cwd: string = process.cwd()): string {
  try {
    return execSync('git branch --show-current', {
      cwd,
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim() || 'HEAD';
  } catch {
    return 'HEAD';
  }
}

/**
 * Check if there are uncommitted changes (unstaged or staged).
 */
export function hasUncommittedChanges(cwd: string = process.cwd()): boolean {
  try {
    const status = execSync('git status --porcelain', {
      cwd,
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    return status.length > 0;
  } catch {
    return false;
  }
}

/**
 * Ensure a branch exists and is checked out.
 * If branch already exists, switches to it. Otherwise creates and checks out.
 */
export function ensureBranch(branchName: string, cwd: string = process.cwd()): GitBranchResult {
  const previousBranch = getCurrentBranch(cwd);
  if (previousBranch === branchName) {
    return { branch: branchName, created: false, previousBranch };
  }

  try {
    const branchExists = execSync(`git branch --list "${branchName}"`, {
      cwd,
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim().length > 0;

    if (branchExists) {
      execSync(`git checkout "${branchName}"`, {
        cwd,
        stdio: ['ignore', 'ignore', 'ignore'],
      });
      return { branch: branchName, created: false, previousBranch };
    } else {
      execSync(`git checkout -b "${branchName}"`, {
        cwd,
        stdio: ['ignore', 'ignore', 'ignore'],
      });
      return { branch: branchName, created: true, previousBranch };
    }
  } catch (err: any) {
    throw new Error(`Failed to create or checkout git branch '${branchName}': ${err.message}`);
  }
}

/**
 * Stage specific files and commit them.
 */
export function commitChanges(
  files: string[],
  message: string,
  cwd: string = process.cwd()
): boolean {
  try {
    if (files.length === 0) return false;

    for (const file of files) {
      execSync(`git add "${file}"`, {
        cwd,
        stdio: ['ignore', 'ignore', 'ignore'],
      });
    }

    execSync(`git commit -m "${message.replace(/"/g, '\\"')}"`, {
      cwd,
      stdio: ['ignore', 'ignore', 'ignore'],
    });

    return true;
  } catch {
    return false;
  }
}

/**
 * Generate copy-pasteable commands to push and create a GitHub PR.
 */
export function generatePrSnippet(branch: string, baseBranch = 'main'): PrSnippet {
  return {
    branch,
    baseBranch,
    gitPushCmd: `git push -u origin ${branch}`,
    ghPrCmd: `gh pr create --title "chore(agent-readiness): ARS 3.0 compliance upgrade" --body "Automated agent readiness remediation manifests generated by Glintbase." --base ${baseBranch}`,
  };
}
